# Qwen/Qwen2.5-VL-7B-Instruct
# multimodel
steps:
  - label: "Unit tests for Qwen/Qwen2.5-VL-7B-Instruct"
    key: "Qwen_Qwen2_5-VL-7B-Instruct_UnitTest"
    agents:
      queue: tpu_v6e_queue
    soft_fail: true
    commands:
      - echo "placeholder"
  - label: "Record unit test result for Qwen/Qwen2.5-VL-7B-Instruct"
    key: "record_Qwen_Qwen2_5-VL-7B-Instruct_UnitTest"
    depends_on: "Qwen_Qwen2_5-VL-7B-Instruct_UnitTest"
    env:
      CI_TARGET: Qwen/Qwen2.5-VL-7B-Instruct
      CI_STAGE: "UnitTest"
      CI_CATEGORY: "multimodel"
    agents:
      queue: tpu_v6e_queue
    commands:
      - |
        .buildkite/scripts/record_step_result.sh Qwen_Qwen2_5-VL-7B-Instruct_UnitTest

  - label: "Integration tests for Qwen/Qwen2.5-VL-7B-Instruct"
    key: "Qwen_Qwen2_5-VL-7B-Instruct_IntegrationTest"
    depends_on: "record_Qwen_Qwen2_5-VL-7B-Instruct_UnitTest"
    agents:
      queue: tpu_v6e_8_queue
    soft_fail: true
    env:
      TEST_MODEL: Qwen/Qwen2.5-VL-7B-Instruct
      TENSOR_PARALLEL_SIZE: 1
      MINIMUM_ACCURACY_THRESHOLD: 0.72
    commands:
      - echo "placeholder"
  - label: "Record integration test result for Qwen/Qwen2.5-VL-7B-Instruct"
    key: "record_Qwen_Qwen2_5-VL-7B-Instruct_IntegrationTest"
    depends_on: "Qwen_Qwen2_5-VL-7B-Instruct_IntegrationTest"
    env:
      CI_TARGET: Qwen/Qwen2.5-VL-7B-Instruct
      CI_STAGE: "IntegrationTest"
      CI_CATEGORY: "multimodel"
    agents:
      queue: tpu_v6e_queue
    commands:
      - |
        .buildkite/scripts/record_step_result.sh Qwen_Qwen2_5-VL-7B-Instruct_IntegrationTest

  - label: "Performance benchmarks for Qwen/Qwen2.5-VL-7B-Instruct"
    key: "Qwen_Qwen2_5-VL-7B-Instruct_Benchmark"
    depends_on: "record_Qwen_Qwen2_5-VL-7B-Instruct_IntegrationTest"
    soft_fail: true
    agents:
      queue: tpu_v6e_queue
    commands:
      - echo "placeholder"
  - label: "Record performance benchmark result for Qwen/Qwen2.5-VL-7B-Instruct"
    key: "record_Qwen_Qwen2_5-VL-7B-Instruct_Benchmark"
    depends_on: "Qwen_Qwen2_5-VL-7B-Instruct_Benchmark"
    env:
      CI_TARGET: Qwen/Qwen2.5-VL-7B-Instruct
      CI_STAGE: "Benchmark"
      CI_CATEGORY: "multimodel"
    agents:
      queue: tpu_v6e_queue
    commands:
      - |
        .buildkite/scripts/record_step_result.sh Qwen_Qwen2_5-VL-7B-Instruct_Benchmark
